server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            format_sql: true
    show_sql: true
  main:
    web-application-type: servlet